### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by Adam-Mazur**
I added an option to not display the divisions, an option to add or remove two boundaries on double tapping the slider, and an option to display a custom tooltip. Only thing I changed with the existing code is the default valueRangePainterCallback to `(range) => range.index % 2 == 1`. I needed those features for my own app, and I thought that someone might find them useful. I also changed the README to include those new features.

### CODE REVIEW

**Comment by sthefanoss** [comment]
Great job, Adam!

Thanks for your improvements. I will review when I get some time.

**Comment by sthefanoss** [comment]
@Adam-Mazur hey, I'm revisiting this repo and liked your changes. But they're made in a pretty old lib version.

Would you still want to add them to the package? Please consider merging the current main into your branch so I can review/test it again.

**Comment by Adam-Mazur** [comment]
Hey @sthefanoss I made those changes quite a long time ago and since I'm not working with flutter anymore I think I will just leave this branch as it is. Of course you can use my code and modify the new version of the library if you want.

**Comment by sthefanoss** [comment]
@Adam-Mazur thanks for your time. I'll add some of your changes later. 
The ability to hide/show spacers is already in!

**Pull request closed without merging**
